default_alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ_"
cipher = "NGQIWFNTQNXWEQNLNILPNFXWNRWIMNTQNCWPBUNNILCEGWYLNPWNBLJNJVTUNGHZLGQNXWRQNGYWGQNBWTUNSWNJQXWCNHBLYNPWNBMPWNHQJUGYLNEYLGQVNBWTUNSWNJQXWCNQBWGZWYNTGMZJLNGUPJQCMYNINGQIVNLNHQPBLGMYNPWNHZWTNJQYLNSWTNZWJYNCEZLHBMGWNHQSWTWPNHZWPWNFXWNVSWYLNPNGQIWFNTGLNJZQJUNIHWBNHQSTNFVPMFWNTLYNTQGWIVNBWNLPHQXNRYMINJNEZLXMCMFNJLFNCECWPNIHLBJUNPJZMHWYNIVRUNIHLBJUNPNBWRQVNPWNFXQVNXWXMNLXMNTQHZWTVNLXMNIHLBJUNCQHLJNFMNXWZQIVFMPNFVPMFNBQNVTWYLBNLRUPNGMTWYNLRUNRUYQNSMPBQNIWNSPWFNBWNFWYLNZLTLNFUPYMPNIWNRUCENFQEYLNSWPBWNSWTXQVNPYUPWBLNBQNSPWFNFUPYWYLNIWNRUCENPYLNPNBWRQVNTQHZWTVNTQGWTYLNRUCENBQNTQGWTYLNRUCENBQNSMPBWNLYWNNBUNSPMNBLFNXWJTWNILPXQVRWXNSTMNJNXMNEYWTNXMJTUNFWNXWXLHLTYQNHBLBNPWNBWNXLNBQNJTUINSWNCYQGWJNHZMXCWIXLNFUPYMNPMNIWNSWNXLNPGWBWNPLFNFLPNSMNZLTNHQEYWTYNXLNXMNVBZUIXWXUFLNQCMFLNHZWCWNSWXNXWTQGWTYNILHZMBNNBLJNGMTMPNGUTWCEYLNBUNXWVFMPNLXMNYELBNBUNFMYUNLYWNHQCEQHNJTUINSPWFNPMNBQNHLJ"

#klic nalezeny M-H algoritmem
best_key = list("LRCTWODEMSJYFXQHKZPBVG_AUIN")

def substitute_decrypt(ciphertext, key, alphabet=default_alphabet):
    """
    Funkce pro dešifrování textu.
    
    Args:
        ciphertext: Vstupní zašifrovaný text
        key: Klíč, který slouží k dešifrování textu
        alphabet: Posloupnost znaků ve formě abecedy
    
    Returns:
        Dešifrovaný text jako datový typ string
    """
    key_array = list(key)
    mapping = {}

    for i in range(len(alphabet)):
        mapping[key_array[i]] = alphabet[i]

    decrypted_text = ""
    for char in ciphertext:
        if char in mapping:
            decrypted_text += mapping[char]
        else:
            decrypted_text += char

    return decrypted_text

print(substitute_decrypt(cipher, best_key))